vim.g.mapleader = ' '
vim.keymap.set({'i','x'}, '<C-l>', '<Esc>'                    , {desc='Escape'})
vim.keymap.set('n', '<leader>a', ':keepjumps normal! ggVG<CR>', {desc='Select All'})
vim.keymap.set({'n','v'}, '<leader>y', '"+y'                  , {desc='Yank'})
vim.keymap.set('n', '<leader>yl', '"+yg_'                     , {desc='Yank Line'})
vim.keymap.set('n', '<leader>yy', '"+yy'                      , {desc='Yank Whole Line'})
vim.keymap.set({'n','v'}, '<leader>p', '"+p'                  , {desc='Paste'})
vim.keymap.set({'n','v'}, '<leader>P', '"+P'                  , {desc='Paste Before'})
vim.keymap.set('n', '<A-k>', ':m -2 <CR>'                     , {desc='Move Line Up'})
vim.keymap.set('n', '<A-j>', ':m +1<CR>'                      , {desc='Move Line Down'})
vim.keymap.set('n', '<A-h>', 'gT'                             , {desc='Tab Next'})
vim.keymap.set('n', '<A-l>', 'gt'                             , {desc='Tab Prev'})
vim.keymap.set('n', '<C-h>', '<C-w>h'                         , {desc='Go To Window Left'})
vim.keymap.set('n', '<C-j>', '<C-w>j'                         , {desc='Go To Window Down'})
vim.keymap.set('n', '<C-k>', '<C-w>k'                         , {desc='Go To Window Up'})
vim.keymap.set('n', '<C-l>', '<C-w>l'                         , {desc='Go To Window Right'})
vim.keymap.set('n', '<C-Up>', ':resize -2<CR>'                , {desc='Window +Height'})
vim.keymap.set('n', '<C-Down>', ':resize +2<CR>'              , {desc='Window -Height'})
vim.keymap.set('n', '<C-Left>', ':vertical resize -2<CR>'     , {desc='Window +Width'})
vim.keymap.set('n', '<C-Right>', ':vertical resize +2<CR>'    , {desc='Window -Width'})
vim.keymap.set('n', '<leader>ws', '<C-w>s'                    , {desc='Split Down'})
vim.keymap.set('n', '<leader>wv', '<C-w>v'                    , {desc='Split Right'})
vim.keymap.set('n', '<leader>wt', '<C-w>T'                    , {desc='Tabify'})
vim.keymap.set('n', '<leader>ww', '<C-w>w'                    , {desc='Switch'})
vim.keymap.set('n', '<leader>fn', ':tabedit<CR>'              , {desc='File New'})
vim.keymap.set('n', '<leader>e', ':Lexplore %:p:h<CR>'        , {desc='Netrw Current File'})
vim.keymap.set('n', '<leader>E', ':Lexplore<CR>'              , {desc='Netrw CWD'})

vim.opt.path:append '**'
vim.opt.mouse = 'a'
vim.opt.completeopt = {'menu', 'menuone', 'noselect'}
vim.opt.expandtab = false
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.incsearch = true
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 20
vim.g.netrw_browse_split = 4
vim.g.netrw_liststyle = 3
